# Graduation Rate vs Non Wavier Rate

In [41]:
import pandas as pd

In [42]:
grad_rates2014 = pd.read_csv('Resources/2014_grad_rates.csv')
grad_rates2015 = pd.read_csv('Resources/2015_grad_rates.csv')
grad_rates2016 = pd.read_csv('Resources/2016_grad_rates.csv')
grad_rates2017 = pd.read_csv('Resources/2017_grad_rates.csv')
grad_rates2018 = pd.read_csv('Resources/2018_grad_rates.csv')
grad_rates2019 = pd.read_csv('Resources/2019_grad_rates.csv')
grad_rates2019.head()

,Corp Id,CORPORATION NAME,Cohort N,Grad N,2019 State Grad Rate,Non-Waiver Grad N,2019 State Non-Waiver Grad Rate
0,15.0,Adams Central Community Schools,99,98,98.99%,95,95.96%
1,25.0,North Adams Community Schools,173,160,92.49%,146,84.39%
2,35.0,South Adams Schools,73,63,86.30%,56,76.71%
3,125.0,M S D Southwest Allen County Schls,578,547,94.64%,528,91.35%
4,225.0,Northwest Allen County Schools,583,560,96.05%,547,93.83%

In [43]:
grad_rates2014 = grad_rates2014.rename(columns={'Non-Waiver\nGrad N' : 'Non-Waiver Grad N' ,
                                                 'Non-Waiver\nGrad Rate': 'Non-Waiver Grad Rate'})
grad_rates2014.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,0015,Adams Central Community Schools,110,105,95.5%,103,93.6%
1,0025,North Adams Community Schools,178,166,93.3%,156,87.6%
2,0035,South Adams Schools,103,99,96.1%,97,94.2%
3,0125,M S D Southwest Allen County Schls,535,508,95.0%,493,92.2%
4,0225,Northwest Allen County Schools,520,504,96.9%,497,95.6%

In [44]:
grad_rates2015 = grad_rates2015.rename(columns={'Non-Waiver\nGrad N' : 'Non-Waiver Grad N' ,
                                                 'Non-Waiver\nGrad Rate': 'Non-Waiver Grad Rate'})
grad_rates2015.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,0015,Adams Central Community Schools,95,90,94.7%,87,91.6%
1,0025,North Adams Community Schools,162,149,92.0%,144,88.9%
2,0035,South Adams Schools,88,83,94.3%,78,88.6%
3,0125,M S D Southwest Allen County Schls,564,535,94.9%,524,92.9%
4,0225,Northwest Allen County Schools,516,497,96.3%,495,95.9%

In [45]:
grad_rates2016 = grad_rates2016.rename(columns={'Non-Waiver\nGrad N' : 'Non-Waiver Grad N' ,
                                                 'Non-Waiver\nGrad Rate': 'Non-Waiver Grad Rate'})
grad_rates2016.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,0015,Adams Central Community Schools,87,86,98.9%,85,97.7%
1,0025,North Adams Community Schools,187,166,88.8%,154,82.4%
2,0035,South Adams Schools,81,73,90.1%,69,85.2%
3,0125,M S D Southwest Allen County Schls,561,542,96.6%,529,94.3%
4,0225,Northwest Allen County Schools,512,495,96.7%,490,95.7%

In [46]:
grad_rates2018 = grad_rates2018.rename(columns={'Corp Id' : 'Corp ID',
                                                'CORPORATION NAME' : 'Corporation Name',
                                                '2018 State Grad Rate' : 'Grad Rate',
                                                 '2018 State Non-Waiver Grad Rate': 'Non-Waiver Grad Rate'})
grad_rates2018.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,15,Adams Central Community Schools,85,81,95.29%,73,85.88%
1,25,North Adams Community Schools,142,136,95.77%,123,86.62%
2,35,South Adams Schools,95,87,91.58%,77,81.05%
3,125,M S D Southwest Allen County Schls,554,532,96.03%,519,93.68%
4,225,Northwest Allen County Schools,564,543,96.28%,536,95.04%

In [47]:
grad_rates2019 = grad_rates2019.rename(columns={'Corp Id' : 'Corp ID',
                                                'CORPORATION NAME' : 'Corporation Name',
                                                '2019 State Grad Rate' : 'Grad Rate',
                                                 '2019 State Non-Waiver Grad Rate': 'Non-Waiver Grad Rate'})
grad_rates2019.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,15.0,Adams Central Community Schools,99,98,98.99%,95,95.96%
1,25.0,North Adams Community Schools,173,160,92.49%,146,84.39%
2,35.0,South Adams Schools,73,63,86.30%,56,76.71%
3,125.0,M S D Southwest Allen County Schls,578,547,94.64%,528,91.35%
4,225.0,Northwest Allen County Schools,583,560,96.05%,547,93.83%