# Graduation Rate vs Non Wavier Rate

In [68]:
%matplotlib notebook

In [69]:
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.pyplot import figure
import seaborn as sns

In [70]:
!pip install seaborn

Requirement already satisfied: seaborn in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (0.11.1)
Requirement already satisfied: numpy>=1.15 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from seaborn) (1.18.5)
Requirement already satisfied: scipy>=1.0 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from seaborn) (1.5.0)
Requirement already satisfied: matplotlib>=2.2 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from seaborn) (3.2.2)
Requirement already satisfied: pandas>=0.23 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from seaborn) (1.0.5)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from matplotlib>=2.2->seaborn) (2.4.7)
Requirement already satisfied: cycler>=0.10 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from matplotlib>=2.2->seaborn) (0.10.0)
Requirement already satisfied: python-dateutil>=2.1 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from matplotlib>=2.2->seaborn) (2.8.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from matplotlib>=2.2->seaborn) (1.2.0)
Requirement already satisfied: pytz>=2017.2 in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from pandas>=0.23->seaborn) (2020.1)
Requirement already satisfied: six in c:\users\matt\anaconda3\envs\pythondata\lib\site-packages (from cycler>=0.10->matplotlib>=2.2->seaborn) (1.15.0)

In [71]:
grad_rates2014 = pd.read_csv('Resources/2014_grad_rates.csv')
grad_rates2015 = pd.read_csv('Resources/2015_grad_rates.csv')
grad_rates2016 = pd.read_csv('Resources/2016_grad_rates.csv')
grad_rates2017 = pd.read_csv('Resources/2017_grad_rates.csv')
grad_rates2018 = pd.read_csv('Resources/2018_grad_rates.csv')
grad_rates2019 = pd.read_csv('Resources/2019_grad_rates.csv')
grad_rates2019.head()

,Corp Id,CORPORATION NAME,Cohort N,Grad N,2019 State Grad Rate,Non-Waiver Grad N,2019 State Non-Waiver Grad Rate
0,15,Adams Central Community Schools,99,98,98.99%,95,95.96%
1,25,North Adams Community Schools,173,160,92.49%,146,84.39%
2,35,South Adams Schools,73,63,86.30%,56,76.71%
3,125,M S D Southwest Allen County Schls,578,547,94.64%,528,91.35%
4,225,Northwest Allen County Schools,583,560,96.05%,547,93.83%

In [72]:
grad_rates2014 = grad_rates2014.rename(columns={'Corp Name' : 'Corporation Name',
                                                'Non-Waiver\nGrad N' : 'Non-Waiver Grad N' ,
                                                 'Non-Waiver\nGrad Rate': 'Non-Waiver Grad Rate'})
grad_rates2014.head()

,Corp ID,Corporation Name,Sch ID,School Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,15,Adams Central Community Schools,0021,Adams Central High School,110,105,95.5%,103,93.6%
1,25,North Adams Community Schools,0029,Bellmont Senior High School,178,166,93.3%,156,87.6%
2,35,South Adams Schools,0023,South Adams High School,103,99,96.1%,97,94.2%
3,125,M S D Southwest Allen County Schls,0047,Homestead Senior High School,535,508,95.0%,493,92.1%
4,225,Northwest Allen County Schools,0091,Carroll High School,520,504,96.9%,497,95.6%

In [73]:
grad_rates2015 = grad_rates2015.rename(columns={'Non-Waiver\nGrad N' : 'Non-Waiver Grad N' ,
                                                 'Non-Waiver\nGrad Rate': 'Non-Waiver Grad Rate'})
grad_rates2015.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,0015,Adams Central Community Schools,95,90,94.7%,87,91.6%
1,0025,North Adams Community Schools,162,149,92.0%,144,88.9%
2,0035,South Adams Schools,88,83,94.3%,78,88.6%
3,0125,M S D Southwest Allen County Schls,564,535,94.9%,524,92.9%
4,0225,Northwest Allen County Schools,516,497,96.3%,495,95.9%

In [74]:
grad_rates2016 = grad_rates2016.rename(columns={'Non-Waiver\nGrad N' : 'Non-Waiver Grad N' ,
                                                 'Non-Waiver\nGrad Rate': 'Non-Waiver Grad Rate'})
grad_rates2016.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,0015,Adams Central Community Schools,87,86,98.9%,85,97.7%
1,0025,North Adams Community Schools,187,166,88.8%,154,82.4%
2,0035,South Adams Schools,81,73,90.1%,69,85.2%
3,0125,M S D Southwest Allen County Schls,561,542,96.6%,529,94.3%
4,0225,Northwest Allen County Schools,512,495,96.7%,490,95.7%

In [75]:
grad_rates2018 = grad_rates2018.rename(columns={'Corp Id' : 'Corp ID',
                                                'CORPORATION NAME' : 'Corporation Name',
                                                '2018 State Grad Rate' : 'Grad Rate',
                                                 '2018 State Non-Waiver Grad Rate': 'Non-Waiver Grad Rate'})
grad_rates2018.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,15,Adams Central Community Schools,85,81,95.29%,73,85.88%
1,25,North Adams Community Schools,142,136,95.77%,123,86.62%
2,35,South Adams Schools,95,87,91.58%,77,81.05%
3,125,M S D Southwest Allen County Schls,554,532,96.03%,519,93.68%
4,225,Northwest Allen County Schools,564,543,96.28%,536,95.04%

In [76]:
grad_rates2019 = grad_rates2019.rename(columns={'Corp Id' : 'Corp ID',
                                                'CORPORATION NAME' : 'Corporation Name',
                                                '2019 State Grad Rate' : 'Grad Rate',
                                                 '2019 State Non-Waiver Grad Rate': 'Non-Waiver Grad Rate'})
grad_rates2019.head()

,Corp ID,Corporation Name,Cohort N,Grad N,Grad Rate,Non-Waiver Grad N,Non-Waiver Grad Rate
0,15,Adams Central Community Schools,99,98,98.99%,95,95.96%
1,25,North Adams Community Schools,173,160,92.49%,146,84.39%
2,35,South Adams Schools,73,63,86.30%,56,76.71%
3,125,M S D Southwest Allen County Schls,578,547,94.64%,528,91.35%
4,225,Northwest Allen County Schools,583,560,96.05%,547,93.83%

In [77]:
columns_to_drop = ['Corp ID',
                  'Cohort N',
                  'Grad N',
                  'Non-Waiver Grad N']
grad_rates2014.drop(columns_to_drop, axis=1, inplace=True)
grad_rates2015.drop(columns_to_drop, axis=1, inplace=True)
grad_rates2016.drop(columns_to_drop, axis=1, inplace=True)
grad_rates2017.drop(columns_to_drop, axis=1, inplace=True)
grad_rates2018.drop(columns_to_drop, axis=1, inplace=True)
grad_rates2019.drop(columns_to_drop, axis=1, inplace=True)

In [88]:
combined_grad_rate = pd.merge(grad_rates2014, grad_rates2015, how = 'outer', on = 'Corporation Name')

combined_grad_rate = combined_grad_rate.rename(columns={
    'Grad Rate_x' : '2014 Grad Rate',
    'Non-Waiver Grad Rate_x' : '2014 Non-Waiver Rate',
    'Grad Rate_y' : '2015 Grad Rate',
    'Non-Waiver Grad Rate_y' : '2015 Non-Waiver Rate'})

combined_grad_rate = pd.merge(combined_grad_rate, grad_rates2016, how = 'outer', on = 'Corporation Name')

combined_grad_rate = combined_grad_rate.rename(columns={
    'Grad Rate' : '2016 Grad Rate',
    'Non-Waiver Grad Rate' : '2016 Non-Waiver Rate'})

combined_grad_rate = pd.merge(combined_grad_rate, grad_rates2017, how = 'outer', on = 'Corporation Name')

combined_grad_rate = combined_grad_rate.rename(columns={
    'Grad Rate' : '2017 Grad Rate',
    'Non-Waiver Grad Rate' : '2017 Non-Waiver Rate'})

combined_grad_rate = pd.merge(combined_grad_rate, grad_rates2018, how = 'outer', on = 'Corporation Name')

combined_grad_rate = combined_grad_rate.rename(columns={
    'Grad Rate' : '2018 Grad Rate',
    'Non-Waiver Grad Rate' : '2018 Non-Waiver Rate'})

combined_grad_rate = pd.merge(combined_grad_rate, grad_rates2019, how = 'outer', on = 'Corporation Name')

combined_grad_rate = combined_grad_rate.rename(columns={
    'Grad Rate' : '2019 Grad Rate',
    'Non-Waiver Grad Rate' : '2019 Non-Waiver Rate'})

column_school_drop = ['School Name']
combined_grad_rate.drop(column_school_drop, axis=1, inplace=True)

combined_grad_rate.head()

,Corporation Name,Sch ID,2014 Grad Rate,2014 Non-Waiver Rate,2015 Grad Rate,2015 Non-Waiver Rate,2016 Grad Rate,2016 Non-Waiver Rate,2017 Grad Rate,2017 Non-Waiver Rate,2018 Grad Rate,2018 Non-Waiver Rate,2019 Grad Rate,2019 Non-Waiver Rate
0,Adams Central Community Schools,0021,95.5%,93.6%,94.7%,91.6%,98.9%,97.7%,97.89%,95.79%,95.29%,85.88%,98.99%,95.96%
1,North Adams Community Schools,0029,93.3%,87.6%,92.0%,88.9%,88.8%,82.4%,90.76%,84.78%,95.77%,86.62%,92.49%,84.39%
2,South Adams Schools,0023,96.1%,94.2%,94.3%,88.6%,90.1%,85.2%,92.79%,89.19%,91.58%,81.05%,86.30%,76.71%
3,M S D Southwest Allen County Schls,0047,95.0%,92.1%,94.9%,92.9%,96.6%,94.3%,96.13%,94.01%,96.03%,93.68%,94.64%,91.35%
4,Northwest Allen County Schools,0091,96.9%,95.6%,96.3%,95.9%,96.7%,95.7%,98.80%,97.00%,96.28%,95.04%,96.05%,93.83%

In [57]:
# x_axis= grad_rates2014['Corporation Name']
# y_axis= grad_rates2014['Non-Waiver Grad Rate']

# # Create bar chart using pyplot
# figure(num=None, figsize=(20,18), dpi=80, facecolor='w', edgecolor='r')
# sns.barplot(x='', y='', data = grad_rates2014)
# # plt.xlim(0,98)
# # plt.figure(figsize=(10,4))
# # tick_locations = [value+0.4 for value in x_axis]
# # plt.xticks(tick_locations, grad_rates2014['Corporation Name'].unique(), rotation= 45)

# # Labels for title and axes
# plt.title('2014 Graduation Rates vs. Actual Graduation Rates')
# plt.ylabel('Non-Waiver Grad Rates')
# plt.xlabel('Corporation Name')

# # Display grid using zorder
# plt.grid(zorder=0)

# # Show bar chart
# plt.show()

sns.lmplot(data=grad_rates2014, x="Grad Rates", y="Non-Waiver Grad Rates", col="time", hue="smoker")

KeyError: "None of [Index(['Grad Rates', 'Non-Waiver Grad Rates', 'smoker', 'time'], dtype='object')] are in the [columns]"